add_lunch_combo frankened_flo-userdebug
add_lunch_combo frankened_hammerhead-userdebug
add_lunch_combo frankened_mako-userdebug
add_lunch_combo frankened_grouper-userdebug
add_lunch_combo frankened_shamu-userdebug